# This is a reusable workflow.
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Release (Shared)

on:
  workflow_call:

jobs:
  manage-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update Release PR
        uses: google-github-actions/release-please-action@v3.5.0
        id: release-pr
        with:
          release-type: node
          include-v-in-tag: false
          extra-files: |
            README.md
            version.js
